### PR TITLE
Ace editor directive

### PR DESCRIPTION
**Pull request by lindakung**
ace editor for user input

### CODE REVIEW

**Comment by seemaullal** [comment]
- Great commits- they are descriptive and helpful
- It would be sweet to have a single ace editor directive for everything but this works for now
- I know you mentioned this was not finished? Or is it? If not, what is there left to do?

This looks fine to merge. :shipit:

**Comment by lindakung** [comment]
@seemaullal we still need to add some functionality to the directive's scope

**Comment by seemaullal** [comment]
@lindakung and @michael you can just merge master into your branch and keep working on this branch before merging then. Thank you!!

**Comment by seemaullal** [comment]
@michaelbbae

**Comment by seemaullal** [comment]
Awesome- go ahead and merge now.

**Pull request merged**
