### PR TITLE
Rooms and exercises directives

### PR DESCRIPTION
**Pull request by iloughman**
Styling of the exercise and room directives is totally open to change. Feel free to make suggestions or just alter what you feel needs retouching.

### CODE REVIEW

**Comment by seemaullal** [comment]
I wasn't able to actually look at the changes you made but from the code, they all seem to be awesome. Thank you for making our site actually look exciting. Go ahead and merge :shipit:

**Comment by lindakung** [comment]
@iloughman it looks awesome! can i change the font?

**Comment by lindakung** [comment]
or you change the font :sheep:

**Comment by lindakung** [comment]
@seemaullal it also fixed our footer issue

**Comment by iloughman** [comment]
I'm fine with a font change. I kinda want to work on it a little more, so I don't think I'm going to merge just yet. I want to use the accordion thing you suggested a while ago.

**Comment by iloughman** [comment]
@lindakung @seemaullal If you guys want to change the fonts please do so, or just let me know what you want me to change.

**Comment by seemaullal** [comment]
@iloughman Nice work! I like what you did and have a few comments-
- to me, it does not seem obvious that you can click on the Easy/Medium/Hard things to expand them or collapse them. Maybe a plus button or something would be helpful
- I think the categories (at least medium and hard) should be collapsed for now because as we add more exercises, things may not fit as well
- Another potential space saving thing (not sure about this one; maybe this should not be an option): Maybe it would be nice to be able to collapse the descriptions also (and just show the top part)
- I don't think this is even related to anything you did, but for the user list in active rooms it would be nice to have them separated by a comma or something (now they are separated by a space)
- Would be interesting if people could pick by category also but I have no idea what this would look like so maybe that is a bad idea

**Comment by seemaullal** [comment]
:shipit: :sheep:

**Comment by iloughman** [comment]
Excellent comments. Merging now, will get these points taken care of in the am.

**Pull request merged**
