### PR TITLE
Arena rooms

### PR DESCRIPTION
**Pull request by ghost**
@seemaullal made a createRoom function that when called, creates a new Firebase child in the '/rooms' node with the logged-in user in it. 

@iloughman figured out that a callback can be placed inside 'mocha.run()' which returns the number of failed test specs, which is equal to the total number of tests when it's first run. We also figured out how to clear the editor so that the test doesn't run on the previous input on page refresh.

The editor only works with monospace fonts. After much hair-pulling, we figured out that the \* selector is the css god and overwrites anything and everything. By placing the beautiful font that @lindakung chose in the 'html' selector, the problem disappeared. 

Let me know if something breaks!

### CODE REVIEW

**Comment by seemaullal** [comment]
@michaelbbae This looks great- you and @iloughman  did good work!

2 questions:
1. Does mocha still run on semicolons, spaces, enter, and backspace? I could be wrong but it looks like it may just be on 'enter'
2. Out of curiosity, how did you fix the problem where it was running the previous input on page load?

Looks like next steps are the ability to add more users to an existing room and also adding a Firebase event when a user passes a test (so other users in the room are alerted). I will add these to the list of issues.

I think you should be good to merge :shipit:

**Comment by ghost** [comment]
Sorry there were a few bugs I need to fix. Will fix then submit another pull request.

**Comment by ghost** [comment]
Bug fixed!

To answer @seemaullal questions: 
1. It's only working on enter now because the tests were running super slow on all those keypresses. I just commented out the array for testing purposes. I know we won't be displaying the actual mocha runner but we might have to think about the fact that we fetch the test from the backend every time we run the test so it always has to make that request.
2. The problem with the persistent input was due to the fact that the input was still stored on the Firebase reference. That meant that even when the page refreshed, the runner still ran the previous code stored on Firebase. By setting that reference to an empty string after the Firebase snapshot is taken, it clears the previous input but the snapshot is preserved for the mocha test to run. If that sounded like gibberish to you, maybe I can explain it better in person.

**Comment by seemaullal** [comment]
For 1, can we store the test after retreiving it the first time? That way we don't have to test every time? I think that just having it run on enter for now is fine. 

Your  explanation for 2 made sense. Thanks!

You can merge now :+1: :shipit:

**Pull request merged**
