### PR TITLE
Wait time

### PR DESCRIPTION
**Pull request by seemaullal**
@lindakung @michaelbbae @iloughman 

This is not a huge update but I added a value to the firebase room that refers to the time the room is created plus 2 minutes (in other words when the waiting room ends and writing code should begin). I also added a timer to the arena that shows how much time is left. This can be used for various things like redirecting from the waiting room to the arena. Let me know if you have questions. Thank you.

### CODE REVIEW

**Comment by lindakung** [comment]
@seemaullal  k

**Comment by seemaullal** [comment]
To be done:
- decide how waiting rooms vs the arena works
- redirect users as necessary

**Comment by ghost** [comment]
:shipit:

**Comment by seemaullal** [comment]
Thank you @michaelbbae / @lindakung . Will merge now.

**Pull request merged**
